In [1]:
import pandas as pd
from pathlib import Path

In [2]:
ruta_directory_zip = Path(
    r"D:\Keralty scripts\automatizaciones_python\retroactivos-clinica-colsanitas\inputs\Clinica ibague anexos 2024 y 2025.zip"
)

In [ ]:
import zipfile

# Abrir el ZIP y leer un archivo específico
with zipfile.ZipFile(ruta_directory_zip, "r") as zip_file:
    # Ver lista de archivos dentro del ZIP
    print(zip_file.namelist())

    df_27000 = pd.read_excel(
        zip_file.open(
            "Clinica ibague anexos 2024 y 2025/27000_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx"
        ),
        sheet_name="ANEXO",
        skiprows=17,
    )

    df_27467 = pd.read_excel(
        zip_file.open(
            "Clinica ibague anexos 2024 y 2025/27467_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx"
        ),
        sheet_name="ANEXO",
        skiprows=17,
    )

    df_30348 = pd.read_excel(
        zip_file.open(
            "Clinica ibague anexos 2024 y 2025/30348_ANEXO_800149384_CLINICA KERALTY IBAGUE (2025).xlsx"
        ),
        sheet_name="ANEXO",
        skiprows=18,
    )

['Clinica ibague anexos 2024 y 2025/27000_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx', 'Clinica ibague anexos 2024 y 2025/27467_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx', 'Clinica ibague anexos 2024 y 2025/30348_ANEXO_800149384_CLINICA KERALTY IBAGUE (2025).xlsx']

In [20]:
# eliminar columnas con Unnamed
df_27000 = df_27000.loc[:, ~df_27000.columns.str.contains("Unnamed")]

df_27000

,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),UVR/VALOR,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $1,996","ANESTESIA UVR $1,509",AYUDANTIA UVR $566,"D SALA Mayor 450 UVR $2,216",MATERIALES,TOTAL,OBSERVACIONES
0,EV,1102,890701,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,890701,12425.0,VALOR,"ISS 2001+57,16%",NaN,NaN,NaN,NaN,NaN,19527.0,NaN
1,EV,706,902210,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,902210,11015.0,VALOR,"ISS 2001+57,16%",NaN,NaN,NaN,NaN,NaN,17311.0,NaN
2,EV,129,890602,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,890602,15095.0,VALOR,"ISS 2001+57,16%",NaN,NaN,NaN,NaN,NaN,23723.0,NaN
3,EV,706,903895,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,NaN,NaN,PROPIA,PROPIA,NaN,NaN,NaN,NaN,NaN,4537.0,NaN
4,EV,706,903856,903856,NITROGENO UREICO,903856,NITROGENO UREICO,No,903856,3665.0,VALOR,"ISS 2001+57,16%",NaN,NaN,NaN,NaN,NaN,5760.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5417,NaN,NaN,NaN,{{Signature1_es_:signer2:signature}},NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5419,NaN,NaN,DUVER DICSON VARGAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LYDA ISABEL BOSA ABRIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5420,NaN,NaN,Agente Especial Interventor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Representante Legal,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5421,NaN,NaN,CC No.1026252683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CC No. 52.887.447,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_27467 = df_27467.loc[:, ~df_27467.columns.str.contains("Unnamed")]

df_27467

,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),UVR/VALOR,TARIFA DEFINIDA,HONORARIO,ANESTESIA,AYUDANTIA,D SALA,MATERIALES,TOTAL,OBSERVACIONES,AMBITO
0,EV,129.0,890474,890474,INTERCONSULTA POR ESPECIALISTA EN NEUROLOGÍA,890474,INTERCONSULTA POR NEUROLOGIA,No,NaN,NaN,PROPIA,NaN,NaN,NaN,NaN,NaN,84637.0,NaN,H-U
1,EV,129.0,890433,890433,INTERCONSULTA POR ESPECIALISTA EN CIRUGÍA DE T...,890433,INTERCONSULTA POR CIRUGIA DE TORAX,No,NaN,NaN,PROPIA,NaN,NaN,NaN,NaN,NaN,64200.0,NaN,H-U
2,PQ,215.0,601101,601101PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE TRANS...,601101PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE TRANS...,No,NaN,NaN,PROPIA,NaN,NaN,NaN,NaN,NaN,1526960.0,Se solicita Replica de Paquete,A-H
3,EV,234.0,324102,324102,LOBECTOMÍA SEGMENTARIA POR TORACOSCOPIA,324102,LOBECTOMIA SEGMENTARIA POR TORACOSCOPIA,Si,323100.0,150.0,"PROPIA HON Demas Componentes ISS 2001+57,16%",2700000,226350.0,84900.0,292962.0,220213,3524425.0,NaN,H
4,PQ,215.0,601103,601103PQ,BIOPSIA CERRADA DE PROSTATA POR SATURACION ABO...,601103PQ,BIOPSIA CERRADA DE PROSTATA POR SATURACION ABO...,No,NaN,NaN,PROPIA,NaN,NaN,NaN,NaN,NaN,1046460.0,Se solicita Replica de Paquete,A-H
5,EV,214.0,386301,386301,ESCLEROSIS DE LESIÓN EN VASOS SANGUÍNEOS VÍA P...,386301,ESCLEROSIS DE LESION EN VASOS SANGUINEOS VIA P...,Si,386301.0,323705.0,"ISS 2001+57,16%",508735,NaN,NaN,NaN,NaN,508735.0,NaN,A-H
6,EV,234.0,324202,324202,LOBECTOMÍA TOTAL PULMONAR POR TORACOSCOPIA,324202,LOBECTOMIA TOTAL PULMONAR POR TORACOSCOPIA,Si,324200.0,200.0,"PROPIA HON Demas Componentes ISS 2001+57,16%",3400000,301800.0,113200.0,388138.0,CONSUMO,4203138.0,NaN,H
7,EV,234.0,345205,345205,PLEURODESIS MECÁNICA POR TORACOSCOPIA,345205,PLEURODESIS MECANICA POR TORACOSCOPIA,Si,349201.0,80.0,"PROPIA HON Demas Componentes ISS 2001+57,16%",1311000,120720.0,45280.0,180467.0,139259,1796726.0,NaN,H
8,EV,234.0,345102,345102,PLEURECTOMÍA PARIETAL POR TORACOSCOPIA,345102,PLEURECTOMIA PARIETAL POR TORACOSCOPIA,Si,345100.0,130.0,"PROPIA HON Demas Componentes ISS 2001+57,16%",2300000,196170.0,73580.0,240573.0,206060,3016383.0,NaN,H
9,PQ,215.0,601102,601102PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE PERIN...,601102PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE PERIN...,No,NaN,NaN,PROPIA,NaN,NaN,NaN,NaN,NaN,866700.0,Se solicita Replica de Paquete,A-H
10,PQ,235.0,501002,501002PQ,BIOPSIA CERRADA (PERCUTANEA) (AGUJA) DE HIGADO...,501002PQ,BIOPSIA CERRADA (PERCUTANEA) (AGUJA) DE HIGADO...,No,NaN,NaN,PROPIA,NaN,NaN,NaN,NaN,NaN,684115.0,Se solicita Replica de Paquete,A-H
11,PQ,234.0,345202,345202PQ,PLEURODESIS QUIMICA POR TORACOSCOPIA - PAQUETE,345202PQ,PLEURODESIS QUIMICA POR TORACOSCOPIA - PAQUETE,No,NaN,NaN,PROPIA,NaN,NaN,NaN,NaN,NaN,7361170.0,Se solicita Replica de Paquete,H
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1. El presente acuerdo para su formalidad debe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,El presente documento es suscrito por las Part...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,# Solicitud,NaN,HABILITACION SEDE,NaN,NOMBRE DE LA SUCURSAL,NaN,NaN,MUNICIPIO,NaN,NaN,NaN,DIRECCION (DOMICILIO DE PRESTACIÓN),NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,27467,NaN,7300102424 -03,NaN,CLINICA KERALTY IBAGUE,NaN,NaN,IBAGUE,NaN,NaN,NaN,CALLE 60 N° 6 - 24 / 38 / 54 CARRERA 6 N° 60 -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,EPS SANITAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESTADOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,{{Signature1_es_:signer2:signature}},NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,DUVER DICSON VARGAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LYDA ISABEL BOSA ABRIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,Agente Especial Interventor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Representante Legal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,CC No.1026252683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CC No. 52887447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df_30348 = df_30348.loc[:, ~df_30348.columns.str.contains("Unnamed")]

df_30348

,TIPO,COD REPS,INTERDEPENDECIA,CODIGO DE HABILITACION - INTERDEPENDENCIA,COD\n(Res Vigente),DESCRIPCION COD (Res Vigente),COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $2,100","ANESTESIA UVR $1,587",AYUDANTIA UVR $595,"D SALA Mayor 450 UVR $2,331",MATERIALES,TOTAL,OBSERVACIONES,xxx
0,EV,1102,NO,NO_APLICA,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,890701,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,20542.0,NaN,NaN
1,EV,706,NO,NO_APLICA,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,902210,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,18211.0,NaN,NaN
2,EV,129,NO,NO_APLICA,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,890602,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,24957.0,NaN,NaN
3,EV,706,NO,NO_APLICA,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,NaN,...,PROPIA,PROPIA,NaN,NaN,NaN,NaN,NaN,4773.0,NaN,NaN
4,EV,706,NO,NO_APLICA,903883,GLUCOSA SEMIAUTOMATIZADA [GLUCOMETRÍA],903883,GLUCOSA SEMIAUTOMATIZADA [GLUCOMETRIA],No,NaN,...,PROPIA,PROPIA,NaN,NaN,NaN,NaN,NaN,4322.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5652,Elaboró: Martha Verónica Cañas C / Coordinador...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5655,VERSIÓN,FECHA,OBSERVACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,ELABORÓ,...,REVISÓ,NaN,NaN,APROBÓ,NaN,NaN,NaN,NaN,NaN,NaN
5656,V1,2025-01-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LUIS FERNANDO MORA ARIZA,...,LUIS FERNANDO MORA ARIZA,NaN,NaN,LUIS FERNANDO MORA ARIZA,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df_27000.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5422 entries, 0 to 5421
Data columns (total 21 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Unnamed: 0                                  0 non-null      float64
 1   TIPO                                        5408 non-null   object
 2   COD REPS                                    5404 non-null   object
 3   COD
(Res Vigente 2336 de 2023)              5301 non-null   object
 4   COD IPS                                     5405 non-null   object
 5   DESCRIPCION IPS                             5406 non-null   object
 6   COD EPS                                     5404 non-null   object
 7   DESCRIPCION CUPS                            5404 non-null   object
 8   HABILITA CONCEPTOS                          5406 non-null   object
 9   COD HOMOLOGO Manual tarifario
(ISS o SOAT)  4054 non-null   object
 10  UVR/VALOR                                   4321 non-null   float64
 11  FORMA DE LIQUIDAR                           5386 non-null   object
 12  TARIFA DEFINIDA                             5408 non-null   object
 13  HONORARIO UVR $1,996                        3696 non-null   object
 14  ANESTESIA UVR $1,509                        3489 non-null   float64
 15  AYUDANTIA UVR $566                          3030 non-null   float64
 16  D SALA Mayor 450 UVR $2,216                 3489 non-null   float64
 17  MATERIALES                                  3471 non-null   object
 18  TOTAL                                       5404 non-null   float64
 19  OBSERVACIONES                               20 non-null     object
 20  Unnamed: 20                                 0 non-null      float64
dtypes: float64(7), object(14)
memory usage: 889.7+ KB